#!/bin/bash -x

#
# Copyright (c) 2006 rPath, Inc.
# This file is distributed under the terms of the MIT License.
# A copy is available at http://www.rpath.com/permanent/mit-license.html
#

# This script acts as the driver for anaconda template generation.  It
# will read the config options in template.conf for customization.  This
# script should not need to be modified

if [ -f ./template.conf ]
	then . template.conf
	else
	    echo "Config file templates.conf is missing"
	    exit 1
fi

mkdir -p $topdir/$subdir/changesets/
mkdir -p $topdir/$subdir/base/

conary --install-label $kernellabel changeset kernel[$kernelflavor] $topdir/$subdir/changesets/kernel-2.6-$arch.ccs

treedir=$destdir
instroot=$treedir/instroot
instrootgr=$treedir/instrootgr

mkdir -p $instroot $instrootgr

sh -x $scriptdir/upd-instroot --install-label "$installlabel" --arch "$arch" $topdir/$subdir/changesets $instroot $instrootgr
sh -x $scriptdir/mk-images $topdir/$subdir/changesets $topdir $instroot $instrootgr $arch "$distroname" $distroversion $subdir $treedir

$scriptdir/makestamp.py --releasestr="$distroname" --arch="$arch" --discNum="1" --baseDir=$subdir/base --packagesDir=$subdir/changesets --pixmapsDir=$subdir/pixmaps --outfile=$topdir/.discinfo

sed -i s,$destdir,,g $destdir/MANIFEST
sed -i 's;,/;,;g' $destdir/MANIFEST

# Fix up font caches
/usr/bin/fc-cache -v $instrootgr/usr/share/fonts/

# Remove the kernel changeset, we dont need to package it
rm -f $topdir/$subdir/changesets/kernel-2.6-$arch.ccs
