#!/bin/sh
# chkconfig: - 82 18
# processname: uwsgi
#

# Source function library
. /etc/init.d/functions

prog="uwsgi"
confdir="/etc/uwsgi/vassals"
logfile="/var/log/uwsgi.log"
pidfile="/var/run/$prog.pid"
args="--emperor $confdir --daemonize $logfile --pidfile $pidfile"
RETVAL=0

start() {
	echo -n $"Starting $prog: "
	daemon $prog $args
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	killproc $prog
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
	return $RETVAL
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	condrestart)
		if [ -f /var/lock/subsys/$prog ]; then
			stop
			start
		fi
		;;
	status)
		status $prog
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|condrestart|status}"
		RETVAL=1
esac

exit $RETVAL
