diff -r aa9b70ccec77 nm-openvpn-service.name.in
--- a/nm-openvpn-service.name.in	Thu Mar 20 23:03:29 2008 -0400
+++ b/nm-openvpn-service.name.in	Thu Mar 20 23:12:32 2008 -0400
@@ -5,5 +5,5 @@ program=@BINDIR@/nm-openvpn-service
 
 [GNOME]
 auth-dialog=@LIBEXECDIR@/nm-openvpn-auth-dialog
-properties=@PREFIX@/${LIB}/libnm-openvpn-properties
+properties=@LIBDIR@/libnm-openvpn-properties
 
