#! /bin/sh
#
#
# chkconfig: 345 92 35
# description: Daemon that manage Samba shares.
#



# Source function library.
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 0
fi

# Avoid using root's TMPDIR
unset TMPDIR

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DESC="Samba sharing daemon"
NAME="smbshared"
DAEMON=/usr/bin/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

#
#	Function that starts the daemon/service.
#
d_start() {
    daemon $DAEMON
}

#
#	Function that stops the daemon/service.
#
d_stop() {
    $DAEMON -k || /bin/true
}


case "$1" in
  start)
	echo -n $"Starting $DESC: $NAME"
	d_start
	echo -n $?
	;;
  stop)
	echo -n $"Stopping $DESC: $NAME"
	d_stop
	echo -n $?
	;;
  restart|force-reload)
	echo -n $"Restarting $DESC: $NAME"
	d_stop
	sleep 1
	d_start
	echo -n $?
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
