#!/bin/bash

execscript=$(basename $0)
scriptdir=%(sysconfdir)s/vmware-tools/scripts/$execscript.d

for file in $scriptdir/*
do
	[ -x $file ] && $file 
done

# To match output from older VMware Tools
echo `date` ": Executing '$0'"
