#!/bin/sh
GOOGLEEARTH_DATA_PATH="/opt/google-earth"
LD_LIBRARY_PATH=/usr/lib64/xorg.nvidia.3d/:/usr/lib/xorg.nvidia.3d/:/usr/lib64/xorg.fglrx.3d/:/usr/lib/xorg.fglrx.3d/:/usr/lib64/xorg.mesa.3d/:/usr/lib/xorg.mesa.3d/:${GOOGLEEARTH_DATA_PATH}:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH
cd "${GOOGLEEARTH_DATA_PATH}/"
exec "./googleearth-bin" --disable-cleanlooks -style GTK $*

