#!/bin/sh

# Make sure mention of running this script shows up in output
echo

# debuggging output until we are sure this handles all cases correctly
set -x

# work around flakeyness in nspluginwrapper
if [ -e /usr/bin/mozilla-plugin-config ]; then
    mozilla-plugin-config -rf
    mozilla-plugin-config -if
    mozilla-plugin-config -l
fi

# it is very important to return success; failure stops the operation
exit 0
