--- Makefile.jau	2006-08-14 15:31:47.000000000 -0400
+++ Makefile	2006-11-06 09:35:54.000000000 -0500
@@ -119,7 +119,7 @@
 clean-examples:
 	rm -rf examples
 
-install: libdhcp.so.1 libdhcp.a html examples
+install: libdhcp.so.1 libdhcp.a examples
 	mkdir -p $(libdir)
 	$(INSTALL) -D -m 0755 libdhcp.so.1 $(libdir)
 	$(INSTALL) -D -m 0644 libdhcp.a $(libdir)
