#!/usr/bin/python

#Copyright 2006-2007 Joseph Tate
#Released under the GPL version 2


from snack import *
import sys
import libuser

VERSION=0.5

ESC = ''
hotkeys[ESC] = ord(ESC)
hotkeys[ord(ESC)] = ESC

def help(screen, text):
    ButtonChoiceWindow(screen, "Help", text, help="Help on help", buttons=['Ok'])

try:
    admin = libuser.admin()
except SystemError, e:
    print >>sys.stderr, "Error:", str(e)
    sys.exit(0)
screen = SnackScreen()

screen.helpCallback(help)
screen.pushHelpLine('<F1> for help | <Tab>/<Alt-Tab> between elements | <F12> next screen | <ESC> cancel')

try:

    nameLabel = Label("Display Name")
    name = Entry(25, "")
    usernameLabel = Label("Username")
    username = Entry(25, "")
    passwordLabel = Label("Password")
    password = Entry(25, "", password=1)
    password2Label = Label("Password (again)")
    password2 = Entry(25, "", password=1)

    okbutton = Button('Ok')
    cancelbutton = Button('Cancel')

    cancelled = True
    msg = "Please complete the data below"
    while True:
        dataWin = EntryWindow(screen, "Create a user", msg,
                [("Display Name", name), ('Username', username), ('Password', password), ('Password (again)', password2)], help="Help text", buttons=[('Ok', 'ok'), ('Cancel', 'cancel', ESC)])
        #Check that the passwords match
        if dataWin[0] == 'cancel':
            break
        if password.value():
            if password.value() == password2.value():
                if len(password.value()) >= 6:
                    #TODO Check that the password passes crack
                    try:
                        #to add the user
                        uname = username.value().strip()
                        gent = admin.initGroup(uname)
                        ent = admin.initUser(uname)
                        ent.set('pw_gecos', name.value().strip())
                        admin.addGroup(gent)
                        ent.set('pw_gid', gent.get('pw_gid'))
                        admin.addUser(ent)

                        #Now set the password
                        admin.setpassUser(ent, password.value(), False)

                        #Add the user to the wheel group
                        wheel = admin.lookupGroupByName('wheel')
                        mem = wheel.get('gr_mem')
                        if uname not in mem:
                            mem.append(username.value())
                            wheel.set('gr_mem', mem)
                            admin.modifyGroup(wheel)
                        cancelled=False
                        break
                    except Exception, e:
                        msg = str(e)
                else:
                    msg = "The password must be at least 6 characters"
            else:
                msg = "The passwords entered do not match"
        else:
            msg = "A password is required"
finally:
    screen.popHelpLine()
    screen.finish()
