#!/bin/bash

if [ $UID != 0 ]
then
    echo "Must be run as root"
    exit
fi

if [ -f /etc/sysconfig/firstrun ]
then
    . /etc/sysconfig/firstrun
else
    RUN_FIRSTRUN="YES"
fi

if [ $RUN_FIRSTRUN ] && [ $RUN_FIRSTRUN == "YES" ]
then
    /usr/sbin/firstrun-user
    echo "RUN_FIRSTRUN=NO" > /etc/sysconfig/firstrun
fi
