#!/bin/bash

if [ $UID != 0 ]
then
    echo "Must be run as root"
    exit
fi

if [ -f /etc/sysconfig/firstrun ]
then
    . /etc/sysconfig/firstrun
else
    RUN_FIRSTRUN="YES"
fi

if [ $RUN_FIRSTRUN ] && [ $RUN_FIRSTRUN == "YES" ]
then
    #echo "Do you wish to configure X? [y/n]"
    #read xconfig
    xconfig="y"
    if [ $xconfig == "y" ] || [ $xconfig == "Y" ]
    then
        echo "Configuring the X Windows System"
        /usr/bin/Xorg -configure :2
        /bin/cp /etc/X11/xorg.conf /etc/X11/xorg.conf.firstrun
        /bin/cp /root/xorg.conf.new /etc/X11/xorg.conf
    fi
    #echo "Please enter your desired username:"
    #read username
    #echo "Please enter full name:"
    #read fullname
    #echo $username
    #echo $fullname
    #/usr/sbin/useradd -c "$fullname" -G wheel $username
    #/usr/bin/passwd $username
    echo "RUN_FIRSTRUN=NO" > /etc/sysconfig/firstrun
fi
