#!/bin/bash
#
# oversite       Oversite checkin at boot
#
# chkconfig: 5 99 99
# description: Oversite checkin at boot

. /etc/init.d/functions


# See how we were called.
case "$1" in
  start)
        echo $"Starting Oversite: "
        touch /var/lock/subsys/oversite
	/usr/sbin/oversite.sh
        ;;
  stop)
        # No action to be taken here
        ;;

  restart|reload)
        $0 start
        ;;

  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
