diff --git a/source/Irrlicht/Makefile b/source/Irrlicht/Makefile
--- a/source/Irrlicht/Makefile
+++ b/source/Irrlicht/Makefile
@@ -75,10 +75,10 @@
 staticlib sharedlib install: SYSTEM = Linux
 STATIC_LIB = libIrrlicht.a
 LIB_PATH = ../../lib/$(SYSTEM)
-INSTALL_DIR = /usr/local/lib
+INSTALL_DIR = /usr/lib$(LIBSELECT)
 sharedlib install: SHARED_LIB = libIrrlicht.so
 staticlib sharedlib: LDFLAGS += --no-export-all-symbols --add-stdcall-alias
-sharedlib: LDFLAGS += -L/usr/X11R6/lib$(LIBSELECT) -lGL -lXxf86vm
+sharedlib: LDFLAGS += -L/usr/lib$(LIBSELECT)/xorg.mesa.3d -L/usr/X11R6/lib$(LIBSELECT) -lGL -lXxf86vm
 staticlib sharedlib: CXXINCS += -I/usr/X11R6/include
 
 #OSX specific options
@@ -129,11 +129,11 @@
 
 # Installs Irrlicht if it was created as shared lib
 install install_osx:
-	$(RM) -r $(INSTALL_DIR)/../include/irrlicht
-	mkdir -p $(INSTALL_DIR)/../include/irrlicht
-	cp ../../include/*.h $(INSTALL_DIR)/../include/irrlicht/
-	cp $(LIB_PATH)/$(SHARED_LIB).$(VERSION) $(INSTALL_DIR)
-	cd $(INSTALL_DIR) && ln -s -f $(SHARED_LIB).$(VERSION) $(SHARED_LIB)
+	$(RM) -r $(DESTDIR)$(INSTALL_DIR)/../include/irrlicht
+	mkdir -p $(DESTDIR)$(INSTALL_DIR)/../include/irrlicht
+	cp ../../include/*.h $(DESTDIR)$(INSTALL_DIR)/../include/irrlicht/
+	cp $(LIB_PATH)/$(SHARED_LIB).$(VERSION) $(DESTDIR)$(INSTALL_DIR)
+	cd $(DESTDIR)$(INSTALL_DIR) && ln -s -f $(SHARED_LIB).$(VERSION) $(SHARED_LIB)
 #	ldconfig -n $(INSTALL_DIR)
 
 TAGS:
