diff -ru ipw2100-0.58.orginal/Makefile ipw2100-0.58/Makefile
--- ipw2100-0.58.orginal/Makefile	2004-11-03 04:28:03.000000000 +0100
+++ ipw2100-0.58/Makefile	2004-11-03 22:47:55.173854920 +0100
@@ -54,7 +54,7 @@
 CONFIG_IEEE80211_CRYPT=$(CONFIG_IEEE80211)
 
 # If you want to build WPA support, uncomment this line:
-# CONFIG_IEEE80211_WPA=$(CONFIG_IEEE80211_CRYPT)
+CONFIG_IEEE80211_WPA=$(CONFIG_IEEE80211_CRYPT)
 
 endif
 
@@ -146,7 +146,7 @@
 # modules are installed into KMISC
 KVER  := $(shell uname -r)
 KSRC := /lib/modules/$(KVER)/build
-KMISC := /lib/modules/$(KVER)/kernel/drivers/net/wireless/ipw2100/
+KMISC := $(DESTDIR)/lib/modules/$(KVER)/kernel/drivers/net/wireless/ipw2100/
 
 # KSRC_OUTPUT should be overridden if you are using a 2.6 kernel that
 # has it's output sent elsewhere via KBUILD_OUTPUT= or O=
@@ -209,7 +209,7 @@
 install: modules
 	install -d $(KMISC)
 	install -m 644 -c $(addsuffix .ko,$(list-m)) $(KMISC)
-	/sbin/depmod -a
+	# /sbin/depmod -a
 ifdef CONFIG_IPW2100_LEGACY_FW_LOAD
 	@echo "Don't forget to copy firmware to /etc/firmware/."
 else
