#!/bin/bash
LIBDIR=@@LIBDIR@@/chromium-browser

# If no args, pass along chrome:// to avoid about:linux-splash (default in
# the development builds), otherwise pass along the args.
#
# Do nothing with this for3 now.  chrome:// is not doing what was expected.
# --new-window and --new-tab are not yet supported in chromium.
if test -z "$1"
then
    SITE=chrome://
else
    SITE=$1
fi

$LIBDIR/chrome --enable-plugins --enable-extensions --enable-greasemonkey --user-agent="Mozilla/5.0 (X11; U; Foresight Linux x86_64; en-US) AppleWebKit/534.0 (KHTML, like Gecko) Chrome/6.0.413.0 Safari/534.0" $@
