#!/bin/bash
LIBDIR=@@LIBDIR@@/chromium-browser

# If no args, pass along chrome:// to avoid about:linux-splash (default in
# the development builds), otherwise pass along the args.
if test -z "$1"
then
    SITE=chrome://
else
    SITE=$1
fi

$LIBDIR/chrome --enable-plugins --enable-extensions --enable-greasemonkey $SITE
