#!/bin/sh
APPNAME=chromium
export CHROME_WRAPPER=%(libdir)s/chromium-browser/chrome
export CHROME_DESKTOP=chromium-browser.desktop
exec %(libdir)s/chromium-browser/chrome "$@"

if [ -f /etc/$APPNAME/default ] ; then
  . /etc/$APPNAME/default
fi

# Prefer user defined CHROMIUM_USER_FLAGS (fron env) over system
# default CHROMIUM_FLAGS (from /etc/$APPNAME/default)
CHROMIUM_FLAGS=${CHROMIUM_USER_FLAGS:-"$CHROMIUM_FLAGS"}
