--- Makefile.old	2005-07-17 04:33:45.000000000 -0700
+++ Makefile	2005-07-17 04:33:01.000000000 -0700
@@ -23,7 +23,7 @@
 endif
 
 ifeq ($(IEEE80211_INC),)
-        IEEE80211_INC := /lib/modules/$(shell uname -r)/include
+        IEEE80211_INC := $(DESTDIR)/lib/modules/$(shell uname -r)/include
 endif
 
 list-m :=
@@ -99,7 +99,7 @@
 # modules are installed into KMISC
 KVER  := $(shell uname -r)
 KSRC := /lib/modules/$(KVER)/build
-KMISC := /lib/modules/$(KVER)/net/ieee80211/
+KMISC := $(DESTDIR)/lib/modules/$(KVER)/net/ieee80211/
 KMISC_INC := /lib/modules/$(KVER)/build/include/net/
 
 # KSRC_OUTPUT should be overridden if you are using a 2.6 kernel that
@@ -184,7 +184,6 @@
 	install -m 644 -c $(addprefix net/,$(ieee80211_inc)) $(IEEE80211_INC)
 	-mkdir -p $(KMISC)/.tmp_versions
 	install -m 644 -c $(addsuffix .mod,$(list-m)) $(KMISC)/.tmp_versions
-	/sbin/depmod -a
 
 uninstall:
 	rm -rf $(addprefix $(KMISC),$(addsuffix .ko,$(list-m)))
