#!/bin/bash
# compiz-start script
#
# hacky autodetection of neccessary options for XGL/AIGLX/NVIDIA
#
# Hanno Boeck, http://www.hboeck.de/
#
# Licensed under the same conditions as compiz itself (MIT or GPL)

GLX_WITH_DIRECT=`glxinfo|grep -c GLX_EXT_texture_from_pixmap`
GLX_WITH_INDIRECT=`LIBGL_ALWAYS_INDIRECT=1 glxinfo|grep -c GLX_EXT_texture_from_pixmap`
GLX_RENDER=`glxinfo|grep -c "OpenGL renderer string: Mesa GLX Indirect"`


COMPIZ_OPTIONS="--replace"

if [ $GLX_WITH_DIRECT -eq 3 ]; then
    if [ $GLX_RENDER -eq 0 ]; then
        echo NVIDIA detected
        export __GL_YIELD="NOTHING" 
    else
        echo XGL detected
    fi
elif [ $GLX_WITH_INDIRECT -eq 3 ]; then
    echo AIGLX detected
    export LIBGL_ALWAYS_INDIRECT=1
    COMPIZ_OPTIONS="$COMPIZ_OPTIONS"
fi

gtk-window-decorator --replace &
/usr/bin/compiz --replace --ignore-desktop-hints glib gconf dbus &
