#!/bin/sh
#
# Update script for Foresight Linux
# Copyright Ken VanDine 2005
# ken AT vandine DOT org
#


if [ `whoami` != "root" ]; then
	echo "------------------------------------------------"
	echo "updatedist must be run with elevated privileges"
	echo "Example: sudo updatedist"
	echo "------------------------------------------------"
	exit
fi

if [ -x 'conary q group-media --full-versions |grep neuroomante'  ]; then
	echo "Updating group-dist and group-media from non-free"
	exec conary update group-dist group-media "$@"
else
	echo "Updating group-dist"
	exec conary update group-dist group-media "$@"
fi
