#!/bin/bash
#
# ipw3945config       make sure ipw firmware is loaded
#
# chkconfig: 2345 06 80
# description: Tries to load the ipw3945 firmware before networking is started
#

. /etc/sysconfig/network

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 0

if [ ! -f /etc/sysconfig/ipw3945config ] ; then
    exit 1
fi

. /etc/sysconfig/ipw3945config

[ "$DEVICE" = "" ] || [ "$MODULE" = "" ] && exit 1

ipwreload() {
    i=1
    while ! $(iwconfig $DEVICE 2>&1 | grep ESSID 2>&1 >/dev/null) && [ $i -le 20 ] ; do
            echo -ne "\n\tReloading $MODULE $i"
            rmmod $MODULE
            modprobe $MODULE
            sleep 1
            i=$((i+1))
    done
}

case "$1" in
    start)
#        ipwreload
	/usr/sbin/ipw3945d
        ;;
    *)
        exit 0
        ;;
esac
