#!/bin/bash
#
# ipw3945config       make sure ipw firmware is loaded
#
# chkconfig: 2345 06 80
# description: Tries to load the ipw3945 firmware before networking is started
#

# Source function library.
. /etc/init.d/functions

. /etc/sysconfig/network

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 0

if [ ! -f /etc/sysconfig/ipw3945config ] ; then
    exit 1
fi

PROG="ipw3945d - regulatory daemon"
. /etc/sysconfig/ipw3945config

[ "$DEVICE" = "" ] || [ "$MODULE" = "" ] && exit 1

ipwreload() {
    i=1
    while ! $(iwconfig $DEVICE 2>&1 | grep ESSID 2>&1 >/dev/null) && [ $i -le 20 ] ; do
            echo -ne "\n\tReloading $MODULE $i"
            rmmod $MODULE
            modprobe $MODULE
            sleep 1
            i=$((i+1))
    done
}

start() {
    echo -n $"Starting $PROG:"
    output=`/usr/sbin/ipw3945d --quiet --pid-file=/var/run/ipw3945d.pid 2>&1>/dev/null`
    RETVAL=$?
    [ $RETVAL = 0 ] && success || failure
    echo
    logger `echo ipw3945d $output`
    return $RETVAL
}

stop() {
    echo -n $"Stopping $PROG:"
    output=`/usr/sbin/ipw3945d --quiet --kill --pid-file=/var/run/ipw3945d.pid 2>&1>/dev/null`
    RETVAL=$?
    [ $RETVAL = 0 ] && success || failure
    echo
    logger `echo ipw3945d $output`
    return $RETVAL
}

RETVAL=0

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo $"Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit $?
